//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationDatabaseProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Thesis_SystemsEntities : DbContext
    {
        public Thesis_SystemsEntities()
            : base("name=Thesis_SystemsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<author> author { get; set; }
        public virtual DbSet<institute> institute { get; set; }
        public virtual DbSet<keyword> keyword { get; set; }
        public virtual DbSet<language> language { get; set; }
        public virtual DbSet<supervisors> supervisors { get; set; }
        public virtual DbSet<thesis> thesis { get; set; }
        public virtual DbSet<topics> topics { get; set; }
        public virtual DbSet<university> university { get; set; }
    }
}
